###############################################################################
#
# Â© Copyright IBM Corp. 2020, 2023, 2024
#
###############################################################################
apiVersion: eventstreams.ibm.com/v1beta2
kind: EventStreams
metadata:
  name: prod-6-brokers
spec:
  version: latest
  license:
    # By installing this product you accept the license terms at https://ibm.biz/ea-license
    accept: false
    license: "L-AUKS-FKVXVL"
    use: "EventAutomationProduction"
  adminApi:
    endpoints:
      - name: ingress
        type: ingress
        host: <HOSTNAME/IP-ADDRESS>
        class: <INGRESS-CLASS>
        containerPort: 8001
  adminUI:
    authentication:
      - type: scram-sha-512
    endpoints:
      - name: ingress
        type: ingress
        host: <HOSTNAME/IP-ADDRESS>
        class: <INGRESS-CLASS>
        containerPort: 3000
  apicurioRegistry:
    endpoints:
      - name: ingress
        type: ingress
        host: <HOSTNAME/IP-ADDRESS>
        class: <INGRESS-CLASS>
        containerPort: 8002
  collector: {}
  restProducer:
    endpoints:
      - name: ingress
        type: ingress
        host: <HOSTNAME/IP-ADDRESS>
        class: <INGRESS-CLASS>
        containerPort: 8003
  strimziOverrides:
    kafka:
      replicas: 6
      authorization:
        type: simple
      config:
        inter.broker.protocol.version: "3.8"
        log.cleaner.threads: 6
        num.io.threads: 24
        num.network.threads: 9
        num.replica.fetchers: 6
        default.replication.factor: 3
        min.insync.replicas: 2
        auto.create.topics.enable: 'false'
      listeners:
        - name: external
          port: 9094
          type: ingress
          tls: true
          authentication:
            type: scram-sha-512
          configuration:
            bootstrap:
              host: <HOSTNAME/IP-ADDRESS>
            brokers:
              - broker: 0
                host: <HOSTNAME/IP-ADDRESS>
              - broker: 1
                host: <HOSTNAME/IP-ADDRESS>
              - broker: 2
                host: <HOSTNAME/IP-ADDRESS>
              - broker: 3
                host: <HOSTNAME/IP-ADDRESS>
              - broker: 4
                host: <HOSTNAME/IP-ADDRESS>
              - broker: 5
                host: <HOSTNAME/IP-ADDRESS>
            class: <INGRESS-CLASS>
        - name: tls
          port: 9093
          type: internal
          tls: true
          authentication:
            type: tls
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: kafka-metrics-config.yaml
            name: prod-6-brokers-metrics-config
      resources:
        requests:
          memory: 8096Mi
          cpu: 2000m
        limits:
          memory: 8096Mi
          cpu: 2000m
      storage:
        type: persistent-claim
        size: 50Gi
        class: <STORAGE-CLASS>
    zookeeper:
      replicas: 3
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: zookeeper-metrics-config.yaml
            name: prod-6-brokers-metrics-config
      storage:
        type: persistent-claim
        size: 4Gi
        class: <STORAGE-CLASS>

